host = "0.0.0.0"
port = 8898
debug_host = "127.0.0.1"
debug_port = 9998
login_token = "dev"
db_host = "127.0.0.1"
db_port = 3306
db_user = "game"
db_password = "123456"
db_name = "game"
redis_host = "127.0.0.1"
redis_port = 6379
redis_user = "default"
redis_password = ""
redis_db = 0
center = false
harbormgr_port = 8008
harbor_port = 8019
web_host = "127.0.0.1"
web_port = 5173
